AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Asset Pilo FastAPI template deployed as an AWS Lambda behind API Gateway using AWS SAM.

Globals:
  Function:
    Runtime: python3.11
    MemorySize: 512
    Timeout: 30
    Handler: app.main.lambda_handler
    Architectures:
      - x86_64

Parameters:
  EnvironmentName:
    Type: String
    Default: local
    Description: Logical environment name used for tagging and naming resources.

Resources:
  FastApiHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: HTTP API for the Asset Pilo FastAPI template.
      StageName: !Ref EnvironmentName

  FastApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${EnvironmentName}-asset-pilo-fastapi"
      Description: FastAPI application packaged as a Lambda function.
      CodeUri: ../../
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref FastApiHttpApi
            Path: /{proxy+}
            Method: ANY

